version: '3.0'

services:
  server:
    build:
      context: ..
      dockerfile: devops/dockerfile.server
    ports:
      - '5003:5002'
  client:
    build:
      context: ..
      dockerfile: devops/dockerfile.client
    ports:
      - '80:80'
    depends_on:
      - server
