version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    working_directory: ~/circleci-ff-workflows
    steps:
      - checkout
      - run:
          name: build client
          command: cd client && npm install && npm run build  # install dependencies
      - run:
          name: build server
          command: cd server && npm install  # setup database
      - run:
          name: test server
          command: cd server && npm test
      - run:
          name: test matcher
          command: cd services/matcher && npm install && npm test
      - run:
          name: Deploy
          command: echo 'not ready yet'
          # command: ssh -o "StrictHostKeyChecking no" root@172.104.86.178 "cd ff && git pull && ./devops/deploy.sh"
