version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/circleci-ff-workflows
    steps:
      - checkout
      - run:
          name: build client
          command: cd client && npm install && npm run build  # install dependencies
      - run:
          name: build server
          command: cd server && npm install  # setup database
      - run:
          name: Run tests
          command: echo 'no test yet'

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-ff-workflows
    steps:
      - checkout
      - run:
          name: deploy to linode
          command: bash devops/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - deploy
                - master
